services:
  nerpybot-migrations:
    build:
      context: .
      target: migrations

  nerpybot:
    build:
      context: .
      target: bot

  nerpybot-web:
    build:
      context: .
      target: web
