name: Release

on:
  push:
    branches:
      - 'main'

jobs:
  bump-and-release:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write   # for pushing commits, tags & creating releases

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Determine bump level
        id: bump
        run: |
          LEVEL=$(echo "${{ github.event.head_commit.message }}" \
            | grep -Eio 'bump: (patch|minor|major)' \
            | awk '{print $2} END {if (NR==0) print "patch"}')
          echo "level=$LEVEL" >> $GITHUB_OUTPUT

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6

      - name: Bump version with uv
        id: version
        run: |
          uv version --frozen --bump ${{ steps.bump.outputs.level }}
          NEW=$(uv version --short)
          echo "new_version=$NEW" >> $GITHUB_OUTPUT

      - name: Commit version bump
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: 'Bump version to v${{ steps.version.outputs.new_version }} - [ci skip]'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
          file_pattern: 'pyproject.toml'
          tagging_message: v${{ steps.version.outputs.new_version }}

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.version.outputs.new_version }}
          name: v${{ steps.version.outputs.new_version }}
          generateReleaseNotes: true
