name: Check and Format Code

on:
  pull_request:
    branches:
      - 'main'

jobs:
  format-check:
    name: Check Code Formatting
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    - uses: astral-sh/ruff-action@v3
      with:
        args: "--version"
    - run: ruff check --fix
    - run: ruff format
    - uses: stefanzweifel/git-auto-commit-action@v6
      with:
          commit_message: 'Format code with ruff'
